name: Docker retention policy

on:
  workflow_dispatch:
  schedule:
     - cron: '16 12 * * *'
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      # https://github.com/actions/delete-package-versions
      - name: Delete all except latest 5 package versions excluding major versions
        uses: actions/delete-package-versions@v4
        with:
          package-name: 'apache_dev_server'
          package-type: 'container'
          min-versions-to-keep: 5
          # delete-only-untagged-versions: 'true'
          ignore-versions: '^(0|[1-9]\\d*)\\.0\\.0$'
